package com.inova8.remediator;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://www.w3.org/ns/sparql-service-description.rdf 
 * @author Auto-generated by schemagen on 06 Dec 2013 09:12 
 */
class SD {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    private static final String NS = "http://www.w3.org/ns/sparql-service-description#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    static String getURI() {return NS;}
    
}
