package com.inova8.remediator;

import java.io.File;
import java.io.FileNotFoundException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import org.junit.Test;

import com.inova8.workspace.RemediatorWorkspace;

import junit.framework.TestCase;



/**
 * The class <code>RemediatorWorkspaceFactoryTest</code> contains tests for the
 * class {@link <code>RemediatorWorkspaceFactory</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 2/12/14 6:44 PM
 *
 * @author PeterL
 *
 * @version $Revision$
 */
public class RemediatorWorkspaceFactoryTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */

	public RemediatorWorkspaceFactoryTest(String name) {
		super(name);
	
	}
	@Test
	public void test_Workspace() {
	
		String workspacePath = "./test/models/Q1";

		try {
			RemediatorWorkspace remediatorWorkspace = RemediatorWorkspaceFactory.create(new File(workspacePath), true);
			assertEquals("[owl, rdf, xml]",remediatorWorkspace.getFileExtensions().toString());
			assertEquals("[http://inova8.com/schema/book-schema, http://inova8.com/people, http://inova8.com/data/books, http://inova8.com/people/void/bad, http://inova8.com/schema/kennedy-schema, http://inova8.com/void/movie-void, http://inova8.com/mapping/people-movie, http://inova8.com/void/people-void, http://inova8.com/people/consolidated, http://inova8.com/schema/people-schema, http://inova8.com/people/void, http://inova8.com/instance-linking/kennedyperson-movieperson, http://inova8.com/people/void/statistics, http://inova8.com/void/book-void, http://inova8.com/schema/movie-schema, http://inova8.com/linking/movie-book, http://inova8.com/mapping/people-kennedy, http://inova8.com/mapping/people-book, http://inova8.com/instance-linking/kennedyperson-bookauthor, http://inova8.com/data/kennedys, http://inova8.com/void/kennedy-void, http://inova8.com/data/movies]",
					remediatorWorkspace.getOntologyURIs().toString());
			assertEquals("file:/C:/Users/PeterL/git/remediator/com.inova8.remediator/./test/models/Q1/data/books.rdf",
					remediatorWorkspace.getPhysicalURI(new URI("http://inova8.com/data/books")).toString());
		} catch (FileNotFoundException e) {
			assert false;
			e.printStackTrace();
		} catch (URISyntaxException e) {
			assert false;
			e.printStackTrace();
		}	
	}

	@Test
	public void test_WorkspaceExtensions() {
	
		String[] extensionsArray = { ".rdf", ".owl" };
		Set<String> extensions = new HashSet<String>(
				Arrays.asList(extensionsArray));
		String workspacePath = "./test/models/Q1";

		try {
			RemediatorWorkspace remediatorWorkspace = RemediatorWorkspaceFactory.create(new File(workspacePath), true,extensions);
			assertEquals("[.rdf, .owl]",remediatorWorkspace.getFileExtensions().toString());
			assertEquals("[http://inova8.com/schema/book-schema, http://inova8.com/people, http://inova8.com/data/books, http://inova8.com/people/void/bad, http://inova8.com/schema/kennedy-schema, http://inova8.com/void/movie-void, http://inova8.com/mapping/people-movie, http://inova8.com/void/people-void, http://inova8.com/people/consolidated, http://inova8.com/schema/people-schema, http://inova8.com/people/void, http://inova8.com/instance-linking/kennedyperson-movieperson, http://inova8.com/people/void/statistics, http://inova8.com/void/book-void, http://inova8.com/schema/movie-schema, http://inova8.com/linking/movie-book, http://inova8.com/mapping/people-kennedy, http://inova8.com/mapping/people-book, http://inova8.com/instance-linking/kennedyperson-bookauthor, http://inova8.com/data/kennedys, http://inova8.com/void/kennedy-void, http://inova8.com/data/movies]",
					remediatorWorkspace.getOntologyURIs().toString());
			assertEquals("file:/C:/Users/PeterL/git/remediator/com.inova8.remediator/./test/models/Q1/data/books.rdf",
					remediatorWorkspace.getPhysicalURI(new URI("http://inova8.com/data/books")).toString());
		} catch (FileNotFoundException e) {
			assert false;
			e.printStackTrace();
		} catch (URISyntaxException e) {
			assert false;
			e.printStackTrace();
		}	
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.inova8.remediator
 * package.sourceFolder = com.inova8.remediator/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = RemediatorWorkspaceFactoryTest
 * testClassType = RemediatorWorkspaceFactory
 */