package com.inova8.remediator;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.OpenOption;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

import org.junit.Before;
import org.junit.Test;

import junit.framework.TestCase;

/**
 * The class <code>RemediatorQueryFactoryTest</code> contains tests for the
 * class {@link <code>RemediatorQueryFactory</code>}
 * 
 * @pattern JUnit Test Case
 * 
 * @generatedBy CodePro at 2/13/14 4:10 PM
 * 
 * @author PeterL
 * 
 * @version $Revision$
 */
public class RemediatorQueryFactoryTest extends TestCase {

	static String readFile(String path, Charset encoding) throws IOException {
		byte[] encoded = Files.readAllBytes(Paths.get(path));
		return encoding.decode(ByteBuffer.wrap(encoded)).toString();
	}

	static void writeFile(String path, String input) throws IOException {
		Files.write(Paths.get(path), input.getBytes(),
				new OpenOption[] { StandardOpenOption.TRUNCATE_EXISTING ,
			StandardOpenOption.CREATE});
	}

	String queryFolder;
	String path;

	/**
	 * Construct new test instance
	 * 
	 * @param name
	 *            the test name
	 */
	public RemediatorQueryFactoryTest(String name) {
		super(name);
	}

	/**
	 * Perform pre-test initialization
	 * 
	 * @throws Exception
	 * 
	 * @see TestCase#setUp()
	 */
	@Override
	@Before
	protected void setUp() throws Exception {
		super.setUp();
		path = "./test/models/";
		queryFolder = "Q1";
	}

	public final void queryPrepare(Integer testNumber) throws Exception {
		String queryString = readFile(path + queryFolder + "/test" + testNumber
				+ "/query.txt", Charset.defaultCharset());
		String simplifiedOpsString = readFile(path + queryFolder + "/test"
				+ testNumber + "/simplifiedops.txt", Charset.defaultCharset());

		RemediatorQuery query = RemediatorQueryFactory.create(queryString);

		writeFile(path + queryFolder + "/test"
				+ testNumber + "/simplifiedops.res.txt", query.getSimplifiedOperations().toString() );
		assertEquals(
				query.getSimplifiedOperations().toString(),
				simplifiedOpsString.replaceAll("\\s+", ""),
				query.getSimplifiedOperations().toString()
						.replaceAll("\\s+", ""));

	}

	/**
	 * Run the RemediatorQuery create(String) method test
	 */

	@Test
	public final void test_create1() throws Exception {
		queryPrepare(1);

	}

	@Test
	public final void test_create2() throws Exception {
		queryPrepare(2);

	}

	@Test
	public final void test_create3() throws Exception {
		queryPrepare(3);

	}

	@Test
	public final void test_create4() throws Exception {
		queryPrepare(4);

	}

	@Test
	public final void test_create5() throws Exception {
		queryPrepare(5);

	}

	@Test
	public final void test_create6() throws Exception {
		queryPrepare(6);

	}

	@Test
	public final void test_create7() throws Exception {
		queryPrepare(7);

	}

	@Test
	public final void test_create8() throws Exception {
		queryPrepare(8);

	}
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = assertTrue = false callTestMethod = true createMain =
 * false createSetUp = true createTearDown = false createTestFixture = false
 * createTestStubs = false methods = create(QString;) package =
 * com.inova8.remediator package.sourceFolder =
 * com.inova8.remediator/src/test/java superclassType = junit.framework.TestCase
 * testCase = RemediatorQueryFactoryTest testClassType = RemediatorQueryFactory
 */