package com.inova8.remediator;

import java.io.File;

import org.junit.Test;

import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.inova8.workspace.Workspace;
import junit.framework.TestCase;

/**
 * The class <code>WorkspaceTest</code> contains tests for the class {@link
 * <code>Workspace</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 2/8/14 2:20 PM
 *
 * @author PeterL
 *
 * @version $Revision$
 */
public class WorkspaceTest extends TestCase {
	String path;
	String URL;
	String queryFolder;
	OntModelSpec voidModelSpec;
	OntModel voidModel;
	OntModelSpec vocabularyModelSpec;
	OntModel vocabularyModel;
	Workspace workspace;
	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public WorkspaceTest(String name) {
		super(name);
		
		
	}
	@Test
	public final void testWorkspace() {
		String[] extensions = { ".rdf", ".owl" };

		path = "./test/models/Q1";

	    workspace = new Workspace(new File(path), true);
	}
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.inova8.remediator
 * package.sourceFolder = com.inova8.remediator/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = WorkspaceTest
 * testClassType = com.inova8.workspace.Workspace
 */